;@
;@!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! WARNING: THIS IS A TEMPLATE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;@
;@!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! README FOR NON-DEVELOPERS !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;@
;@  When you first open the project, this file will get copied to user.ini if it does not already
;@  exist. You should close this file and edit user.ini instead.
;@
;@  If you are here because it doesn't exist, open the project in the VSC IDE, that should create
;@  it. Alternatively, make a copy of this file and remove this notice manually. All of the lines
;@  that start with ;@ can be deleted.
;@
;@!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;@
;@!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! README FOR DEVELOPERS !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;@
;@  Changes to this file should mostly include documentation and defaults for settings that would
;@  typically be changed by a user. Try to keep any extremely advanced options out of it. Users
;@  can still copy those settings from the main file if they want to.
;@
;@  You can include comments to developers by starting a line with `;@`. Those lines will not be
;@  copied to user.ini.
;@
;@!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;
; ==================================== USER CONFIGURATION FILE ====================================
;
;   This file can/should be used to store your personal settings so they don't get clobbered when
;   you update. You can also easily backup this file between updates to ensure your settings are
;   not lost.
;
;   If you put a setting in here that also exists in the ini files, it will be overridden by the
;   value you put in here. Although this file will start with documentation on most settings and
;   options, it will not be automatically updated as that would defeat its purpose. So, be sure
;   to still check for new available settings/options. You can look in the ini files directly or
;   compare this file to the .user.new.ini file which this file was created from.
;
;   ** NOTE **
;   If you purchased your OSCR as a prebuilt or a kit, you should check your SD card to see if it
;   has a user.ini on it. Your seller might have provided you with one that matches your hardware
;   configuration for your convenience.
;
;
;   # Instructions
;
;   Lines like this which start with ; are purely comments/instructions, so don't delete the ;
;   Lines that start with with ;! are overrides which you can uncomment to enable/change.
;
;   Below is a setting which commented and is showing you the option name and default value:
;     ;!region = auto
;
;   Below is the same setting which has been uncommented and changed:
;     region = na
;
;   Many settings are simply a toggle - on or off. We use "true" and "false" for those.
;     updater = true
;     debugging = false
;
;   Some settings have specific options to choose from. Those settings will list their options
;   before the actual place to set them. When updating, you might want to check if there are any
;   new options available with the update.
;


; =
[platformio]

;
; ================ CUSTOM CONFIG ================
; Use a specific config instead of the default of all HW versions.
;

; Custom version defined at the end of this file
;!default_envs = MyOSCR

; SaveTheHero HW3-ALTER pre-built
;!default_envs = SaveTheHeroV3

; StarshadeRETRO HW5 pre-builts and full-kits with integrated ATmega2560.
;!default_envs = StarshadeV5


; =
[oscr]

;
; ================ FIRMWARE L10N ================
;  Choose your language and region.
;
; ===== LANGUAGES =====
;   - en    : English
;

;!language = en


;
; ===== REGIONS =====
; Choose a region below. Note that region does not dictate cartridge region compatibility. It is
; merely for display/UI purposes, such as displaying "Genesis" or "Mega Drive". In the future, it
; is possible that some cores might make assumptions based on this setting. For instance, if a
; cartridge has multiple versions for different regions but they all look the same initially, the
; core might use this setting as the region to try first to improve detection time.
;
; If a language is set, auto will make some assumptions. For instance, if the language is set to
; English, you will see "Mega Drive/Genesis", but with something other than English, you will see
; the name "Mega Drive", since that was its name everywhere outside NA. If you don't like what it
; chooses, simply change it.
;
;   - auto  : Global
;   - na    : North America
;   - eu    : Europe
;   - as    : Asia (Japan)
;   - af    : Africa
;   - oc    : Oceania
;   - sa    : South America
;   - an    : Antarctica
;

;!region = auto


;
; ================ POWER SAVING =================
; Save power when idle! These power saving options are fairly unobtrusive. You can configure the
; exact methods used later in this file.
;
; Note: The OSCR is only considered idle when sitting on a menu or prompt,
;       if it is actively dumping a cartridge, etc, it will not enter power
;       saving mode.
;

;!powersaving = true


;
; ================ STABILITY FIX ================
; Enable this if your ATmega2560 is unstable when running at 3.3V. It will slow the clock to 8MHz
; when running at 3.3V to increase stability. Note that this will make dumping at 3.3V take about
; twice as the amount of time. You might consider getting a new ATmega2560 instead if you dump a
; lot of 3.3V cartridges.
;

;!mega3v3fix = false


;
; ========= CONFIGURATION FILE SUPPORT ==========
; Allow setting some options via a config file. See the config.txt file the supported settings.
;

;!config = true


;
; =============== UPDATER SUPPORT ===============
; Allows software to identify the hardware version and other features of an OSCR connected via
; USB using serial. It is used by the updater available at OSCR.tools.
;

;!updater = true


;
; ================== DEBUGGING ==================
; Enable debug messages via serial. This can provide helpful additional information via serial
; console to aid in troubleshooting. It requires a lot of extra program space so it's generally
; good to keep it disabled unless you have an issue you are trying to fix (or are a developer).
;
; Note: Cannot be used with, and will be ignored by, ANSI serial.
;

;!debugging = false


; =
[hardware]

;
; ============= ON-BOARD ATMEGA2560 =============
; Support for having an on-board ATmega2560. Only available on HW5R8 or newer.
;
; module      : ATmega2560 is attached as a module
; integrated  : ATmega2560 is direct on-board
;

;!atmega = module


;
; ====== CLOCK SIGNAL GENERATOR (CLOCKGEN) ======
; Support for the Si5351 clock signal generator.
;
; Should be enabled if you have one of:
; - Adafruit Clock Generator module
; - Clone of an Adafruit Clock Generator module
; - The on-board Si5351
;

;!clockgen = false


;
; ============ REAL TIME CLOCK (RTC) ============
; Support for having a real-time clock.
;
; Enable if you have one of:
; - RTC installed on directly on your main board.
; - The StarshadeRETRO Clock Generator module (as it includes RTC).
;

;!rtc = false


;
; ===== RTC TYPE =====
; You can select the type here.
;
; Options:
;   - DS3231  : Standard
;   - DS1307  : Custom
;

;!rtc_type = DS3231


;
; ===== AUTOMATIC VOLTAGE SELECT (VSELECT) ======
; Support for VSELECT (TPS2113 or similar).
;

;!vselect = false


; =
[cores]

;
; ================ CORE SUPPORT =================
; Choose the system cores you want enabled here.
;
; auto  : accept the default for the hardware version
; true  : enable the core
; false : disable the core
;

;!arc = auto
;!atari2600 = auto
;!atari5200 = auto
;!atari7800 = auto
;!atari8 = auto
;!atarijaguar = auto
;!atarilynx = auto
;!bally = auto
;!c64 = auto
;!colv = auto
;!cps3 = auto
;!fairchild = auto
;!flash = auto
;!flash16 = auto
;!gbx = auto
;!gpc = auto
;!intv = auto
;!leapster = auto
;!littlejammer = auto
;!littlejammerpro = auto
;!loopy = auto
;!md = auto
;!msx = auto
;!n64 = auto
;!nes = auto
;!ngp = auto
;!ody2 = auto
;!pce = auto
;!pcw = auto
;!poke = auto
;!pv1000 = auto
;!rcastudio2 = auto
;!sfm = auto
;!sms = auto
;!snes = auto
;!st = auto
;!superacan = auto
;!supervision = auto
;!satellaview = auto
;!ti99 = auto
;!tommypyuuta = auto
;!trs80 = auto
;!vectrex = auto
;!vic20 = auto
;!vboy = auto
;!vsmile = auto
;!wonderswan = auto
;!selftest = auto


; =
[options]

;
; =========== UNIQUE DIRECTORY METHOD ===========
; The method used when generating a unique directory name.
;
; Options:
;   - auto       : Decide based on available features
;   - increment  : Use an incrementing number
;   - rtc        : Use the date and time
;   - both       : Use both
;

;!unique.method = auto


;
; ============ POWER SAVING OPTIONS =============
; Fine tune the settings for power saving mode (if enabled).
;


;
; Time before dozing (ms)
;

;!powersaving.idle.drowse = 30000


;
; Time before going to sleep (ms)
;

;!powersaving.idle.sleep = 60000


;
; Methods used
;

;!powersaving.methods = display-dim|display-off|clock-slow


;
; ================= SD OPTIONS ==================
; SD card options.
;

;
; Increase SD speed but consume higher current at idle
;

;!lib.sd.fast = yes


;
; Minimize SD library size. Decreases program size but reduces features.
;

;!lib.sd.min = no


;
; Enable UTF8 filename support
;

;!lib.sd.utf8 = false


;
; ============== PERFORMANCE FLAGS ==============
; These flags allow you to trade resources for faster dumping. Enabling speed-or-death will use
; more SRAM, while enabling any of the rest mostly only increases PROGMEM usage.
;
;   - inline-crc32    : Force CRC32 methods to always inline
;   - inline-n64      : Force N64 functions to always inline
;   - shared-file     : Force some sharedFile functions to always inline
;   - file-read       : Force file reading functions to always inline
;   - file-write      : Force file writing functions to always inline
;   - speed-or-death  : Copy CRC32 table into SRAM instead of reading from PROGMEM
;
; == NOTE ==
; You can select multiple flags by using the bitwise OR operator (|), for example:
;   performance.flags = inline-crc32|inline-n64
;

;!performance.flags =


;
; =========== CUSTOM HARDWARE VERSION ===========
; Configure your own custom hardware version here. This can feel a bit complex, but you can copy
; one of the hardware configs from platformio.ini to start with to make it a little easier.
;
; Some options have suboptions. When an option has a suboption it will end with a colon (:).
;
; For example, `board:ATmega2560:` has several suboptions. Choose one and add it to the end, such
; as `board:ATmega2560:standard`.
;
; Always put the board, the output, and then the input, in that order.
;
; ===== BOARDS ======
;   - board:ATmega2560:   ATmega2560-based MCUs
;     - standard          Standard bootloader for any Arduino MEGA module (or clone)
;     - standard:vs       Standard bootloader with extra support for vselect
;     - standard:obm      Standard bootloader with extra support for an integrated mega (and vselect)
;     - minimal           Minimal bootloader (removes options that aren't needed with the OSCR)
;     - minimal:vs        Minimal bootloader with extra support for vselect
;     - minimal:obm       Minimal bootloader with extra support for an integrated mega (and vselect)
;
; If you are burning a new bootloader, this is how you choose which one.
;
; If you have a modified bootloader, choose the option that corresponds with it.
;
; If you are aren't sure what this means, stick to the standard bootloader. Even
; if it's wrong, it won't hurt anything. If you choose one of the others and it's
; wrong, you can break something.
;
;
; ===== Inputs =====
;   - input:rotary            Rotary dial (such as with the MINI 12864 on HW4 and HW5)
;   - input:button2           2 buttons as input (such as with HW2 and HW3)
;   - input:button1           1 button as input (such as with HW1)
;
;
; ===== Outputs =====
;   - output:oled             SSD1306 OLED display module (typical with HW1 through HW3)
;   - output:lcd:             MINI 12864 module (typical with with HW4 and HW5)
;     - mks                   Makerbase MKS MINI 12864 (most common)
;     - btt                   BigTreeTech MINI 12864
;     - starshade             StarshadeRETRO OSCR 12864
;
;
; ===== Bound Input+Outputs =====
;   - io:serial:              Use serial communication via USB instead of a display.
;     - ascii                 ASCII serial input and output, "classic" serial.
;     - ansi                  ANSI serial output, requires a terminal which supports ANSI control codes.
;


;
; == HARDWARE CONFIG ==
; Here you can setup your own custom hardware. This section is not commented out because it isn't
; overriding any settings in platformio.ini.
;

[hardware:mine]
extends =
  board:ATmega2560:minimal    ; Minimal bootloader
  output:lcd:mks              ; MKS MINI module display
  input:rotary                ; MKS MINI module input
hardware.version = 5          ; hardware version
option.core.sms.adapter = hw5 ; Use HW5's SMS slot
option.core.gg.adapter = hw5  ; Use HW5's GG slot


;
; == BUILD CONFIG  ==
; This is the build configuration used for the above hardware configuration. You don't normally
; need to change this.
;

[env:MyOSCR]
extends = hardware:mine
build_src_flags =
  ${this.arch.build_src_flags}
  ${this.output.build_flags}
  -D HW_VERSION=${this.hardware.version}
build_flags =
  ${this.arch.build_flags}
extra_scripts =
  ${this.arch.extra_scripts}
lib_deps =
  ${this.arch.lib_deps}
  ${this.output.lib_deps}
  ${this.input.lib_deps}

