; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
name = OSCR Firmware
description = Firmware for the OSCR
default_envs = HardwareV5, HardwareV4, HardwareV3, HardwareV2, HardwareV1, SerialASCII, SerialANSI

[oscr]

;
; !! START OF USER SETTINGS !!
;
; Note: Most setting values are case sensitive!
;

;
; [ HARDWARE CONFIGURATION ]
; Configure the firmware for your specific hardware here.
;
; true  : enabled
; false	: disabled
;

; [ ON-BOARD ATMEGA2560 ]
; Support for having an on-board ATmega2560
;
; Only available on HW5R8 or newer.
;
onboard_atmega = false
;

; [ CLOCK SIGNAL GENERATOR (CLOCKGEN) ]
; Support for the Si5351 clock signal generator.
;
; Enable if you have one of:
; - Adafruit Clock Generator module
; - Clone of an Adafruit Clock Generator module
; - The on-board Si5351
;
clockgen = true
;

; [ REAL TIME CLOCK (RTC) ]
; Support for having a real-time clock.
;
; Enable if you have one of:
; - Adafruit Clock Generator module
; - Clone of an Adafruit Clock Generator module
; - The on-board Si5351
;
rtc = false
;
; Type of RTC - One of: DS3231, DS1307
rtc_type = DS3231
;

; [ AUTOMATIC VOLTAGE SELECT (VSELECT) ]
; Support for VSELECT (TPS2113 or similar).
;
vselect = false
;

;
; [ FIRMWARE L10N ]
; Choose your language and region.
;
; Languages
; - EN		: English
;
language = EN
;
; Regions
; - AUTO	: Global
; - NA		: North America
; - EU		: Europe
; - AS		: Asia
; - AF		: Africa
; - OC		: Oceania
; - SA		: South America
; - AN		: Antarctica
;
region = AUTO
;

;
; [ FIRMWARE OPTIONS ]
; Toggle various firmware options here to customize things to your liking.
;
; true  : enabled
; false	: disabled
;


; [ UNIQUE DIRECTORY METHOD ]
; The method used when generating unique directories.
;
; Options:
;  AUTO				: Decide based on available features
;  INCREMENT	: Use an incrementing number
;  RTC				: Use the date and time
;  BOTH				: Use both
;
unique.method = AUTO
;

; [ POWER SAVING OPTIONS ]
; Save power when idle! These power saving options are fairly unobtrusive.
;
; Note: The OSCR is only considered idle when sitting on a menu or prompt,
;       if it is actively dumping a cartridge, etc, it will not enter power
;       saving mode.
;
powersaving = true
;
; Time before dozing (ms)
powersaving.idle.dim = 30000
;
; Time before going to sleep (ms)
powersaving.idle.sleep = 60000
;
; Dim the display backlight when dozing
powersaving.methods.display.dim = true
;
; Turn off the display backing when sleeping
powersaving.methods.display.off = true
;
; Slow the clockspeed to 8MHz when dozing or sleeping
powersaving.methods.clockspeed = true
;

; [ ATMEGA2560 3.3V STABILITY FIX (3V3FIX)]
; Enable if your mega is unstable when running on 3.3V
;
mega3v3fix = false
;

; [ CONFIGURATION FILE SUPPORT ]
; Allow configuring some options via a config file.
;
config = false
;

; [ UPDATER SUPPORT ]
; Allows software to identify the hardware version and other features of an OSCR connected via USB.
;
updater = true
;

; [ DEBUGGING ]
; Enable debug messages via serial. Cannot be used with, and will be ignored by, ANSI serial.
;
debugging = false
;


;
; [ CORE SUPPORT ]
; Toggle the enabled cores here.
;
; auto  : accept the default for the hardware version
; true  : enable the core
; false	: disable the core
;
core.arc = auto
core.atari2600 = auto
core.atari5200 = auto
core.atari7800 = auto
core.atari8 = auto
core.atarijaguar = auto
core.atarilynx = auto
core.bally = auto
core.c64 = auto
core.colv = auto
core.cps3 = auto
core.fairchild = auto
core.flash = auto
core.flash16 = auto
core.gbx = auto
core.gpc = auto
core.intv = auto
core.leapster = auto
core.littlejammer = auto
core.littlejammerpro = auto
core.loopy = auto
core.md = auto
core.msx = auto
core.n64 = auto
core.nes = auto
core.ngp = auto
core.ody2 = auto
core.pce = auto
core.pcw = auto
core.poke = auto
core.pv1000 = auto
core.rcastudio2 = auto
core.sfm = auto
core.sms = auto
core.snes = auto
core.st = auto
core.superacan = auto
core.supervision = auto
core.sv = auto
core.ti99 = auto
core.tommypyuuta = auto
core.trs80 = auto
core.vectrex = auto
core.vic20 = auto
core.vboy = auto
core.vsmile = auto
core.wonderswan = auto

core.selftest = auto

;
; [ HARDWARE VERSIONS ]
; Configurations of the various hardware versions. Some of these can be tweaked a little.
;
; Always put the architecture, the output, and then the input, in that order.
;
; Architectures
; - arch:atmega2560				: ATmega2560 support (module or on-board)
;
; Inputs
; - input:rotary					: Rotary dial (such as with the MINI 12864 on HW4 and HW5)
; - input:2button					: 2 buttons as input (such as with HW2 and HW3)
; - input:1button					: 1 button as input (such as with HW1)
;
; Outputs
; - output:lcd:*					: Use the MINI 12864 module (such as with HW4 and HW5). See suboptions below.
; - output:oled						: Use the OLED module (such as with HW1 through HW3).
;
; Bound Input+Outputs
; - io:serial:*						: Use serial communication via USB. See suboptions below.
;
;
; [Suboptions] output:lcd
; - output:lcd:mks 				: MKS MINI 12864
; - output:lcd:btt 				: BigTreeTech MINI 12864
; - output:lcd:starshade	: StarshadeRETRO OSCR 12864
;
; [Suboptions] Serial
; - io:serial:ascii				: ASCII serial input and output, "classic" serial.
; - io:serial:ansi				: ANSI serial output, requires a terminal which supports ANSI control codes.
;

;
; [ HARDWARE VERSION 5 ]
;
[hardware:5]
extends =
	arch:atmega2560
	output:lcd:starshade
	input:rotary
hardware.version = 5
core.options.sms.adapter = SMSOPT_SMS_ADAPTER_HW5
core.options.gg.adapter = SMSOPT_GG_ADAPTER_HW5

;
; [ HARDWARE VERSION 4 ]
;
[hardware:4]
extends =
	arch:atmega2560
	output:lcd:mks
	input:rotary
hardware.version = 4
core.options.sms.adapter = SMSOPT_SMS_ADAPTER_HW5
core.options.gg.adapter = SMSOPT_GG_ADAPTER_HW5

;
; [ HARDWARE VERSION 3 ]
;
[hardware:3]
extends =
	arch:atmega2560
	output:oled
	input:2button
hardware.version = 3

;
; [ HARDWARE VERSION 2 ]
;
[hardware:2]
extends =
	arch:atmega2560
	output:oled
	input:2button
hardware.version = 2

;
; [ HARDWARE VERSION 1 ]
;
[hardware:1]
extends =
	arch:atmega2560
	output:oled
	input:1button
hardware.version = 1

;
; [ SERIAL: ASCII ]
; Set hardware version as needed.
;
[hardware:serial:ascii]
extends =
	arch:atmega2560
	io:serial:ascii
hardware.version = 5

;
; [ SERIAL: ANSI ]
; Set hardware version as needed.
;
[hardware:serial:ansi]
extends =
	arch:atmega2560
	io:serial:ansi
hardware.version = 5


;
;
; !! END OF USER SETTINGS !!
;
; You shouldn't modify anything below unless you know what you are doing.
;


;
; [ DEFAULTS ]
; Architecture defaults
;
[defaults]
neopixel = false
core.options.sms.adapter = SMSOPT_SMS_ADAPTER_ALL
core.options.gg.adapter = SMSOPT_GG_ADAPTER_ALL
core.options.sg1000.adapter = SMSOPT_SG1000_ADAPTER_ALL
output.serial_type = ASCII
output.lcd_type =
output.build_flags =
output.lib_deps =
input.lib_deps =

;
; [ ENVIRONMENT ]
;
[env]
extends = core
lib_compat_mode = strict
build_flags =
	-D WANT_UPDATER=${oscr.updater}
	-D WANT_DEBUGGING=${oscr.debugging}
	-D OPTION_UNIQUE_DIRECTORY_METHOD=UNQDIR_${oscr.unique.method}
	-D CORE_ARC=CORE_ENABLE_${oscr.core.arc}
	-D CORE_2600=CORE_ENABLE_${oscr.core.atari2600}
	-D CORE_5200=CORE_ENABLE_${oscr.core.atari5200}
	-D CORE_7800=CORE_ENABLE_${oscr.core.atari7800}
	-D CORE_ATARI8=CORE_ENABLE_${oscr.core.atari8}
	-D CORE_JAGUAR=CORE_ENABLE_${oscr.core.atarijaguar}
	-D CORE_LYNX=CORE_ENABLE_${oscr.core.atarilynx}
	-D CORE_BALLY=CORE_ENABLE_${oscr.core.bally}
	-D CORE_C64=CORE_ENABLE_${oscr.core.c64}
	-D CORE_COLV=CORE_ENABLE_${oscr.core.colv}
	-D CORE_CPS3=CORE_ENABLE_${oscr.core.cps3}
	-D CORE_FAIRCHILD=CORE_ENABLE_${oscr.core.fairchild}
	-D CORE_FLASH=CORE_ENABLE_${oscr.core.flash}
	-D CORE_FLASH16=CORE_ENABLE_${oscr.core.flash16}
	-D CORE_GBX=CORE_ENABLE_${oscr.core.gbx}
	-D CORE_GPC=CORE_ENABLE_${oscr.core.gpc}
	-D CORE_INTV=CORE_ENABLE_${oscr.core.intv}
	-D CORE_LEAP=CORE_ENABLE_${oscr.core.leapster}
	-D CORE_LJ=CORE_ENABLE_${oscr.core.littlejammer}
	-D CORE_LJPRO=CORE_ENABLE_${oscr.core.littlejammerpro}
	-D CORE_LOOPY=CORE_ENABLE_${oscr.core.loopy}
	-D CORE_MD=CORE_ENABLE_${oscr.core.md}
	-D CORE_MSX=CORE_ENABLE_${oscr.core.msx}
	-D CORE_N64=CORE_ENABLE_${oscr.core.n64}
	-D CORE_NES=CORE_ENABLE_${oscr.core.nes}
	-D CORE_NGP=CORE_ENABLE_${oscr.core.ngp}
	-D CORE_ODY2=CORE_ENABLE_${oscr.core.ody2}
	-D CORE_PCE=CORE_ENABLE_${oscr.core.pce}
	-D CORE_PCW=CORE_ENABLE_${oscr.core.pcw}
	-D CORE_POKE=CORE_ENABLE_${oscr.core.poke}
	-D CORE_PV1000=CORE_ENABLE_${oscr.core.pv1000}
	-D CORE_RCA=CORE_ENABLE_${oscr.core.rcastudio2}
	-D CORE_SFM=CORE_ENABLE_${oscr.core.sfm}
	-D CORE_SMS=CORE_ENABLE_${oscr.core.sms}
	-D CORE_SNES=CORE_ENABLE_${oscr.core.snes}
	-D CORE_ST=CORE_ENABLE_${oscr.core.st}
	-D CORE_SUPERACAN=CORE_ENABLE_${oscr.core.superacan}
	-D CORE_WSV=CORE_ENABLE_${oscr.core.supervision}
	-D CORE_SV=CORE_ENABLE_${oscr.core.sv}
	-D CORE_TI99=CORE_ENABLE_${oscr.core.ti99}
	-D CORE_PYUUTA=CORE_ENABLE_${oscr.core.tommypyuuta}
	-D CORE_TRS80=CORE_ENABLE_${oscr.core.trs80}
	-D CORE_VECTREX=CORE_ENABLE_${oscr.core.vectrex}
	-D CORE_VIC20=CORE_ENABLE_${oscr.core.vic20}
	-D CORE_VBOY=CORE_ENABLE_${oscr.core.vboy}
	-D CORE_VSMILE=CORE_ENABLE_${oscr.core.vsmile}
	-D CORE_WONDERSWAN=CORE_ENABLE_${oscr.core.wonderswan}
	-D CORE_SELFTEST=CORE_ENABLE_${oscr.core.selftest}
lib_deps =
	SPI
	Wire

;
; Bound Input/Outputs
;

[io:serial:ascii]
output.type = SERIAL
output.serial_type = ASCII
input.type = SERIAL

[io:serial:ansi]
monitor_speed = 115200
output.type = SERIAL
output.serial_type = ANSI
input.type = SERIAL

;
; Inputs
;

[input:2button]
input.type = 2BUTTON

[input:1button]
input.type = 1BUTTON

[input:rotary]
input.type = ROTARY
input.lib_deps =
	paulstoffregen/FreqCount@^1.3
	mathertel/RotaryEncoder@^1.6.0

;
; Outputs
;

[output:oled]
output.type = SSD1306
output.build_flags =
output.lib_deps =
	olikraus/U8g2@^2.36.18

[output:lcd]
extends =
	peripheral:neopixel
neopixel = true
output.type = OS12864
output.build_flags =
	${this.neopixel.build_flags}
output.lib_deps =
	olikraus/U8g2@^2.36.18
	${this.neopixel.lib_deps}

[output:lcd:mks]
extends = output:lcd
output.lcd_type = LCD_MKS
neopixel.dir = NORMAL
output.build_flags =
	${output:lcd.output.build_flags}
	-D OPTION_NEOPIXEL_ORDER=NPXL_${this.neopixel.dir}

[output:lcd:starshade]
extends = output:lcd
output.lcd_type = LCD_SSRETRO
neopixel.dir = REVERSE
output.build_flags =
	${output:lcd.output.build_flags}
	-D OPTION_NEOPIXEL_ORDER=NPXL_${this.neopixel.dir}

[output:lcd:btt]
extends = output:lcd
output.lcd_type = LCD_BTT
neopixel.dir = REVERSE
output.build_flags =
	${output:lcd.output.build_flags}
	-D OPTION_NEOPIXEL_ORDER=NPXL_${this.neopixel.dir}

;
; Peripherals
;

[peripheral:neopixel]
color.background.red = 100
color.background.green = 0
color.background.blue = 100
color.notification.red = 100
color.notification.green = 100
color.notification.blue = 0
color.error.red = 100
color.error.green = 0
color.error.blue = 0
neopixel.build_flags =
	-D OPTION_LCD_BG_RED=${this.color.background.red}
	-D OPTION_LCD_BG_GREEN=${this.color.background.green}
	-D OPTION_LCD_BG_BLUE=${this.color.background.blue}
	-D OPTION_LCD_NOTIF_RED=${this.color.notification.red}
	-D OPTION_LCD_NOTIF_GREEN=${this.color.notification.green}
	-D OPTION_LCD_NOTIF_BLUE=${this.color.notification.blue}
	-D OPTION_LCD_ERROR_RED=${this.color.error.red}
	-D OPTION_LCD_ERROR_GREEN=${this.color.error.green}
	-D OPTION_LCD_ERROR_BLUE=${this.color.error.blue}
neopixel.lib_deps =
	adafruit/Adafruit NeoPixel@^1.15.4

;
; Architectures
;

[arch:atmega2560]
extends = defaults
build_type = release
cppstd = gnu++1z
cstd = gnu11
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 9600
app.filebrowser.filename.max = 20
app.filebrowser.files.max = 50
app.filebrowser.sort.len = 10
class.path.depth_max = 5
board_bootloader.file = bootloader/avr/stk500boot_v2_mega2560-min.hex
platform_packages =
	toolchain-atmelavr
build_unflags =
	-std=gnu++11
	-std=gnu11
	-flto
	-Og
arch.build_src_flags =
	${env.build_flags}
	-Os
	-flto=auto
	-D USING_ONBOARD_ATMEGA=${oscr.onboard_atmega}
	-D OSCR_LANGUAGE=LANG_${oscr.language}
	-D OSCR_REGION=REGN_${oscr.region}
	-D WANT_CLOCKGEN=${oscr.clockgen}
	-D WANT_VSELECT=${oscr.vselect}
	-D WANT_3V3FIX=${oscr.mega3v3fix}
	-D WANT_RTC=${oscr.rtc}
	-D WANT_CONFIG=${oscr.config}
	-D RTC_TYPE=RTCOPT_${oscr.rtc_type}
	-D WANT_POWERSAVING=${oscr.powersaving}
	-D WANT_POWERSAVING_DISPLAY_DIM=${oscr.powersaving.methods.display.dim}
	-D WANT_POWERSAVING_DISPLAY_OFF=${oscr.powersaving.methods.display.off}
	-D WANT_POWERSAVING_SLOWCLOCK=${oscr.powersaving.methods.clockspeed}
	-D OPTION_POWERSAVING_IDLE_DIM=${oscr.powersaving.idle.dim}
	-D OPTION_POWERSAVING_IDLE_SLEEP=${oscr.powersaving.idle.sleep}
	-D UPD_BAUD=${this.monitor_speed}
	-D UI_FILE_BROWSER_FILENAME_MAX=${this.app.filebrowser.filename.max}
	-D UI_FILE_BROWSER_FILES_MAX=${this.app.filebrowser.files.max}
	-D UI_FILE_BROWSER_FILE_SORT_LEN=${this.app.filebrowser.sort.len}
	-D PATH_MAX_DEPTH=${this.class.path.depth_max}
arch.build_flags =
	${env.build_flags}
	-Os
	-std=${this.cppstd}
	-flto=auto
	-fno-exceptions
	-ffunction-sections
	-fdata-sections
	-mcall-prologues
	-Wno-unknown-pragmas
	-Wl,--relax
	-Wl,-flto=auto
arch.extra_scripts =
	scripts/build_flags.py
arch.lib_deps =
	${env.lib_deps}
	greiman/SdFat@^2.3.1
	etherkit/Etherkit Si5351@^2.2.0
	adafruit/RTClib@^2.1.4

;
; Final Hardware Environments
;

[env:HardwareV5]
extends = hardware:5
build_src_flags =
	${this.arch.build_src_flags}
	${this.output.build_flags}
	-D HW_VERSION=${this.hardware.version}
	-D HARDWARE_INPUT_TYPE=INPUT_${this.input.type}
	-D HARDWARE_OUTPUT_TYPE=OUTPUT_${this.output.type}
	-D OPTION_LCD_TYPE=${this.output.lcd_type}
	-D OPTION_SERIAL_OUTPUT=SERIAL_${this.output.serial_type}
	-D WANT_NEOPIXEL=${this.neopixel}
	-D OPTION_SMS_ADAPTER=${this.core.options.sms.adapter}
	-D OPTION_GG_ADAPTER=${this.core.options.gg.adapter}
	-D OPTION_SG1000_ADAPTER=${this.core.options.sg1000.adapter}
build_flags =
	${this.arch.build_flags}
extra_scripts =
	${this.arch.extra_scripts}
lib_deps =
	${this.arch.lib_deps}
	${this.output.lib_deps}
	${this.input.lib_deps}



[env:HardwareV4]
extends = hardware:4
build_src_flags =
	${this.arch.build_src_flags}
	${this.output.build_flags}
	-D HW_VERSION=${this.hardware.version}
	-D HARDWARE_INPUT_TYPE=INPUT_${this.input.type}
	-D HARDWARE_OUTPUT_TYPE=OUTPUT_${this.output.type}
	-D OPTION_LCD_TYPE=${this.output.lcd_type}
	-D OPTION_SERIAL_OUTPUT=SERIAL_${this.output.serial_type}
	-D WANT_NEOPIXEL=${this.neopixel}
	-D OPTION_SMS_ADAPTER=${this.core.options.sms.adapter}
	-D OPTION_GG_ADAPTER=${this.core.options.gg.adapter}
	-D OPTION_SG1000_ADAPTER=${this.core.options.sg1000.adapter}
build_flags =
	${this.arch.build_flags}
extra_scripts =
	${this.arch.extra_scripts}
lib_deps =
	${this.arch.lib_deps}
	${this.output.lib_deps}
	${this.input.lib_deps}



[env:HardwareV3]
extends = hardware:3
build_src_flags =
	${this.arch.build_src_flags}
	${this.output.build_flags}
	-D HW_VERSION=${this.hardware.version}
	-D HARDWARE_INPUT_TYPE=INPUT_${this.input.type}
	-D HARDWARE_OUTPUT_TYPE=OUTPUT_${this.output.type}
	-D OPTION_LCD_TYPE=${this.output.lcd_type}
	-D OPTION_SERIAL_OUTPUT=SERIAL_${this.output.serial_type}
	-D WANT_NEOPIXEL=${this.neopixel}
	-D OPTION_SMS_ADAPTER=${this.core.options.sms.adapter}
	-D OPTION_GG_ADAPTER=${this.core.options.gg.adapter}
	-D OPTION_SG1000_ADAPTER=${this.core.options.sg1000.adapter}
build_flags =
	${this.arch.build_flags}
extra_scripts =
	${this.arch.extra_scripts}
lib_deps =
	${this.arch.lib_deps}
	${this.output.lib_deps}
	${this.input.lib_deps}



[env:HardwareV2]
extends = hardware:2
build_src_flags =
	${this.arch.build_src_flags}
	${this.output.build_flags}
	-D HW_VERSION=${this.hardware.version}
	-D HARDWARE_INPUT_TYPE=INPUT_${this.input.type}
	-D HARDWARE_OUTPUT_TYPE=OUTPUT_${this.output.type}
	-D OPTION_LCD_TYPE=${this.output.lcd_type}
	-D OPTION_SERIAL_OUTPUT=SERIAL_${this.output.serial_type}
	-D WANT_NEOPIXEL=${this.neopixel}
	-D OPTION_SMS_ADAPTER=${this.core.options.sms.adapter}
	-D OPTION_GG_ADAPTER=${this.core.options.gg.adapter}
	-D OPTION_SG1000_ADAPTER=${this.core.options.sg1000.adapter}
build_flags =
	${this.arch.build_flags}
extra_scripts =
	${this.arch.extra_scripts}
lib_deps =
	${this.arch.lib_deps}
	${this.output.lib_deps}
	${this.input.lib_deps}



[env:HardwareV1]
extends = hardware:1
build_src_flags =
	${this.arch.build_src_flags}
	${this.output.build_flags}
	-D HW_VERSION=${this.hardware.version}
	-D HARDWARE_INPUT_TYPE=INPUT_${this.input.type}
	-D HARDWARE_OUTPUT_TYPE=OUTPUT_${this.output.type}
	-D OPTION_LCD_TYPE=${this.output.lcd_type}
	-D OPTION_SERIAL_OUTPUT=SERIAL_${this.output.serial_type}
	-D WANT_NEOPIXEL=${this.neopixel}
	-D OPTION_SMS_ADAPTER=${this.core.options.sms.adapter}
	-D OPTION_GG_ADAPTER=${this.core.options.gg.adapter}
	-D OPTION_SG1000_ADAPTER=${this.core.options.sg1000.adapter}
build_flags =
	${this.arch.build_flags}
extra_scripts =
	${this.arch.extra_scripts}
lib_deps =
	${this.arch.lib_deps}
	${this.output.lib_deps}
	${this.input.lib_deps}



[env:SerialASCII]
extends = hardware:serial:ascii
build_src_flags =
	${this.arch.build_src_flags}
	${this.output.build_flags}
	-D HW_VERSION=${this.hardware.version}
	-D HARDWARE_INPUT_TYPE=INPUT_${this.input.type}
	-D HARDWARE_OUTPUT_TYPE=OUTPUT_${this.output.type}
	-D OPTION_LCD_TYPE=${this.output.lcd_type}
	-D OPTION_SERIAL_OUTPUT=SERIAL_${this.output.serial_type}
	-D WANT_NEOPIXEL=${this.neopixel}
	-D OPTION_SMS_ADAPTER=${this.core.options.sms.adapter}
	-D OPTION_GG_ADAPTER=${this.core.options.gg.adapter}
	-D OPTION_SG1000_ADAPTER=${this.core.options.sg1000.adapter}
build_flags =
	${this.arch.build_flags}
extra_scripts =
	${this.arch.extra_scripts}
lib_deps =
	${this.arch.lib_deps}
	${this.output.lib_deps}
	${this.input.lib_deps}



[env:SerialANSI]
extends = hardware:serial:ansi
build_src_flags =
	${this.arch.build_src_flags}
	${this.output.build_flags}
	-D HW_VERSION=${this.hardware.version}
	-D HARDWARE_INPUT_TYPE=INPUT_${this.input.type}
	-D HARDWARE_OUTPUT_TYPE=OUTPUT_${this.output.type}
	-D OPTION_LCD_TYPE=${this.output.lcd_type}
	-D OPTION_SERIAL_OUTPUT=SERIAL_${this.output.serial_type}
	-D WANT_NEOPIXEL=${this.neopixel}
	-D WANT_DEBUGGING=false
	-D OPTION_SMS_ADAPTER=${this.core.options.sms.adapter}
	-D OPTION_GG_ADAPTER=${this.core.options.gg.adapter}
	-D OPTION_SG1000_ADAPTER=${this.core.options.sg1000.adapter}
build_flags =
	${this.arch.build_flags}
extra_scripts =
	${this.arch.extra_scripts}
lib_deps =
	${this.arch.lib_deps}
	${this.output.lib_deps}
	${this.input.lib_deps}

[env:Databases]
platform = symlink://${PROJECT_DIR}/databases
