; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html



;
;
; =================================================================================================
;
;
; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! ATTENTION !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;
;
; Settings moved to ./config.d/ to keep things more organized and because this file gets overwritten by PIO sometimes.
;
; You can configure your own hardware in ./user.ini to avoid losing changes on update!
;
;
; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! ATTENTION !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;
;
; =================================================================================================
;
;



[platformio]
name = OSCR Firmware
description = Firmware for the OSCR
default_envs = HardwareV5, HardwareV4, HardwareV3, HardwareV2, HardwareV1, SerialASCII, SerialANSI
extra_configs =
  config.d/0[0-9]-*
  config.d/1[0-9]-*
  config.d/2[0-9]-*
  config.d/3[0-9]-*
  config.d/4[0-9]-*
  config.d/5[0-9]-*
  config.d/6[0-9]-*
  config.d/7[0-9]-*
  config.d/8[0-9]-*
  config.d/9[0-9]-*
