;
; [ HARDWARE VERSION 5 ]
;
[hardware:5]
extends =
  board:ATmega2560:standard
  output:lcd:mks
  input:rotary
hardware.version = 5
option.core.sms.adapter = hw5

;
; [ HARDWARE VERSION 4 ]
;
[hardware:4]
extends =
  board:ATmega2560:standard
  output:lcd:mks
  input:rotary
hardware.version = 4

;
; [ HARDWARE VERSION 3 ]
;
[hardware:3]
extends =
  board:ATmega2560:standard
  output:oled
  input:button2
hardware.version = 3

;
; [ HARDWARE VERSION 2 ]
;
[hardware:2]
extends =
  board:ATmega2560:standard
  output:oled
  input:button2
hardware.version = 2

;
; [ HARDWARE VERSION 1 ]
;
[hardware:1]
extends =
  board:ATmega2560:standard
  output:oled
  input:button1
hardware.version = 1

;
; [ SERIAL: ASCII ]
; Set hardware version as needed.
;
[hardware:serial:ascii]
extends =
  board:ATmega2560:standard
  io:serial:ascii
hardware.version = 5
option.lib.sd.dedicated = true

;
; [ SERIAL: ANSI ]
; Set hardware version as needed.
;
[hardware:serial:ansi]
extends =
  board:ATmega2560:standard
  io:serial:ansi
hardware.version = 5
option.lib.sd.dedicated = true
; Debugging must be off
oscr.debugging = false

