;
; Basic Firmware Configuration
;

[oscr]

;
; ================ FIRMWARE L10N ================
;  Choose your language and region.
;
; ===== LANGUAGES =====
;   - en    : English
;

language = en


;
; ===== REGIONS =====
; Choose a region below. Note that region does not dictate cartridge region compatibility. It is
; merely for display/UI purposes, such as displaying "Genesis" or "Mega Drive". In the future, it
; is possible that some cores might make assumptions based on this setting. For instance, if a
; cartridge has multiple versions for different regions but they all look the same initially, the
; core might use this setting as the region to try first to improve detection time.
;
; If a language is set, auto will make some assumptions. For instance, if the language is set to
; English, you will see "Mega Drive/Genesis", but with something other than English, you will see
; the name "Mega Drive", since that was its name everywhere outside NA. If you don't like what it
; chooses, simply change it.
;
;   - auto  : Global
;   - na    : North America
;   - eu    : Europe
;   - as    : Asia (Japan)
;   - af    : Africa
;   - oc    : Oceania
;   - sa    : South America
;   - an    : Antarctica
;

region = auto


;
; ================ POWER SAVING =================
; Save power when idle! These power saving options are fairly unobtrusive. You can configure the
; exact methods used later in this file.
;
; Note: The OSCR is only considered idle when sitting on a menu or prompt,
;       if it is actively dumping a cartridge, etc, it will not enter power
;       saving mode.
;

powersaving = true


;
; ================ STABILITY FIX ================
; Enable this if your ATmega2560 is unstable when running at 3.3V. It will slow the clock to 8MHz
; when running at 3.3V to increase stability. Note that this will make dumping at 3.3V take about
; twice as the amount of time. You might consider getting a new ATmega2560 instead if you dump a
; lot of 3.3V cartridges.
;

mega3v3fix = false


;
; ========= CONFIGURATION FILE SUPPORT ==========
; Allow setting some options via a config file. See the config.txt file the supported settings.
;

config = false


;
; =============== UPDATER SUPPORT ===============
; Allows software to identify the hardware version and other features of an OSCR connected via
; USB using serial. It is used by the updater available at OSCR.tools.
;

updater = true


;
; ================== DEBUGGING ==================
; Enable debug messages via serial. This can provide helpful additional information via serial
; console to aid in troubleshooting. It requires a lot of extra program space so it's generally
; good to keep it disabled unless you have an issue you are trying to fix (or are a developer).
;
; Note: Cannot be used with, and will be ignored by, ANSI serial.
;

debugging = false


[hardware]

;
; ============= ON-BOARD ATMEGA2560 =============
; Support for having an on-board ATmega2560. Only available on HW5R8 or newer.
;
; module      : ATmega2560 is attached as a module
; integrated  : ATmega2560 is direct on-board
;
atmega = module
;

;
; ====== CLOCK SIGNAL GENERATOR (CLOCKGEN) ======
; Support for the Si5351 clock signal generator.
;
; Should be enabled if you have one of:
; - Adafruit Clock Generator module
; - Clone of an Adafruit Clock Generator module
; - The on-board Si5351
;
clockgen = false
;

;
; ============ REAL TIME CLOCK (RTC) ============
; Support for having a real-time clock.
;
; Enable if you have one of:
; - RTC installed on directly on your main board.
; - The StarshadeRETRO Clock Generator module (as it includes RTC).
;
rtc = false
;

;
; ===== RTC TYPE =====
; You can select the type here.
;
; Options:
;   - DS3231  : Standard
;   - DS1307  : Custom
;
rtc_type = DS3231
;

;
; ===== AUTOMATIC VOLTAGE SELECT (VSELECT) ======
; Support for VSELECT (TPS2113 or similar).
;
vselect = false
;

; EOF
