;
; Core Enable/Disable Toggles
;

[cores]
;
; [ CORE SUPPORT ]
; Toggle the enabled cores here.
;
; auto  : accept the default for the hardware version
; true  : enable the core
; false : disable the core
;
arc = auto
atari2600 = auto
atari5200 = auto
atari7800 = auto
atari8 = auto
atarijaguar = auto
atarilynx = auto
bally = auto
c64 = auto
colv = auto
cps3 = auto
fairchild = auto
flash = auto
flash16 = auto
gbx = auto
gpc = auto
intv = auto
leapster = auto
littlejammer = auto
littlejammerpro = auto
loopy = auto
md = auto
msx = auto
n64 = auto
nes = auto
ngp = auto
ody2 = auto
pce = auto
pcw = auto
poke = auto
pv1000 = auto
rcastudio2 = auto
sfm = auto
sms = auto
snes = auto
st = auto
superacan = auto
supervision = auto
satellaview = auto
ti99 = auto
tommypyuuta = auto
trs80 = auto
vectrex = auto
vic20 = auto
vboy = auto
vsmile = auto
wonderswan = auto

selftest = auto
