;
; Firmware Options
;

[options]
;
; =========== UNIQUE DIRECTORY METHOD ===========
; The method used when generating a unique directory name.
;
; Options:
;   - auto       : Decide based on available features
;   - increment  : Use an incrementing number
;   - rtc        : Use the date and time
;   - both       : Use both
;
unique.method = auto
;


;
; ============ POWER SAVING OPTIONS =============
; Fine tune the settings for power saving mode (if enabled).
;

;
; Time before dozing (ms)
;
powersaving.idle.drowse = 30000

;
; Time before going to sleep (ms)
;
powersaving.idle.sleep = 60000

;
; Methods used
;
powersaving.methods = display-dim|display-off|clock-slow
;


;
; ================ CRDB OPTIONS =================
; Options for CRDB (cartridge/mapper/etc databases)
;
; ====== ID32 Multimatching Method ======
; ID32s are generally a checksum of a predetermined area of a cart
; used to identify the cartridge. Some cores, such as the NES core,
; use them to avoid you having to select the cart settings manually.
;
; These options lets you choose which method to use for that matching.
;

;
; == NOTE ==
; You should generally leave this alone. However, if you are having
; issues getting specific carts to match, you could try changing the
; method to a different one.
;
; The `id32b` method is closest to the one used in the old firmware.
;
; The `id32a` method uses a different region (starting address).
;
; Using `either` will make it more likely the cart gets matched to
; something, but will also increase the number of incorrect matches
; found.
;
; Using `both` will significantly decrease the number of incorrect
; matches, but will also make it more likely no match is found.
;
; ==== Fields ====
; Choose which fields to use. You can select the cart fields and
; database fields separately.
;
;  Options:
;   id32a       : Use only the first (id32a) checksum.
;   id32b       : Use only the second (id32b) checksum.
;
; Cart Fields
crdb.id32.multimatch.cart = id32a|id32b
; Database Fields
crdb.id32.multimatch.database = id32b
;

; ==== Method ====
; Choose the method to use. Only applicable when both of the above
; are using both fields.
;
;  Options:
;   any        : Match any checksum (`a=a|a=b|b=a|b=b`).
;   either     : Match either checksum (`a=a|b=b`).
;   all        : Match all checksums (`a=a&b=b`).
;   invert     : Invert `either` (`a=b|b=a`) or `all` (`a=b&b=a`).
;   or_invert  : Matches normally or inverted.
;
crdb.id32.multimatch.method = any
;

;
; ================= SD OPTIONS ==================
; SD card options.
;

;
; Increase SD speed but consume higher current at idle
;
lib.sd.fast = yes
;

;
; Minimize SD library size. Decreases program size but reduces features.
;
lib.sd.min = no
;

;
; Enable UTF8 filename support
;
lib.sd.utf8 = false
;

;
; Enable dedicated SPI
;
lib.sd.dedicated = false
;


;
; ============== PERFORMANCE FLAGS ==============
; These flags allow you to trade resources for faster dumping. Enabling speed-or-death
; will use more SRAM, while enabling any of the rest mainly increases PROGMEM usage.
;
; inline-crc32    : Force CRC32 methods to always inline
; inline-n64      : Force N64 functions to always inline
; shared-file     ; Force some sharedFile functions to always inline*
; file-read       ; Force file reading functions to always inline*
; file-write      ; Force file writing functions to always inline*
; speed-or-death  : Copy CRC32 table into SRAM instead of reading from PROGMEM
;
performance.flags =
;

;
; ========== NOTE ==========
;
; For the "optimal" N64 dumping speed (resources used vs time saved), set:
;    lib.sd.fast = yes
;    performance.flags = inline-crc32|inline-n64
;
; Fastest possible dumping requires a name brand SD card.
;
; ---- BENCHMARKS ----
;
; These times were as measured by the OSCR firmware using built-in RTC-backed method. If you want
;  to compare using the firmware, you *must* have RTC enabled for accurate timing. The millis()
;  function is unreliable for measuring time when the MCU is heavily loaded. It will tend to report
;  that less time has passed than actually has. It should only be used as a general measurement.
;
; Setup Used:
;  - OSCR HW5 Revision 8 with full on-board ATmega2560, Clock Gen, RTC (DS3231), VSELECT, and CBUS
;  - OSCR Seven-slot top PCB (fully populated capacitors)
;  - StarshadeRETRO OSCR MINI12864 LCD module
;  - 32GB SanDisk Ultra SDHC UHS-I full-size SD card (100 MB/s)
;
; 64MB Dump Times:
;  Unoptimized
;   -> 10 min,  6 sec
;
;  lib.sd.fast
;   ->  8 min,  2 sec
;
;  lib.sd.fast & inline-crc32|inline-n64
;   ->  6 min, 38 sec
;
;  lib.sd.fast & inline-crc32|inline-n64|speed-or-death
;   ->  6 min, 23 sec
;
;  lib.sd.fast & inline-crc32|inline-n64|speed-or-death|shared-file|file-read|file-write
;   ->  5 min, 50 sec
;
