;
; Serial Input/Output
;

[io:serial:ascii]
output.type = SERIAL
output.serial_type = ASCII
input.type = SERIAL

[io:serial:ansi]
monitor_speed = 115200
output.type = SERIAL
output.serial_type = ANSI
input.type = SERIAL
