;
; NeoPixel
;

[peripheral:neopixel]
color.background.red = 100
color.background.green = 0
color.background.blue = 100
color.notification.red = 100
color.notification.green = 100
color.notification.blue = 0
color.error.red = 100
color.error.green = 0
color.error.blue = 0
neopixel.build_flags =
  -D OPTION_LCD_BG_RED=${this.color.background.red}
  -D OPTION_LCD_BG_GREEN=${this.color.background.green}
  -D OPTION_LCD_BG_BLUE=${this.color.background.blue}
  -D OPTION_LCD_NOTIF_RED=${this.color.notification.red}
  -D OPTION_LCD_NOTIF_GREEN=${this.color.notification.green}
  -D OPTION_LCD_NOTIF_BLUE=${this.color.notification.blue}
  -D OPTION_LCD_ERROR_RED=${this.color.error.red}
  -D OPTION_LCD_ERROR_GREEN=${this.color.error.green}
  -D OPTION_LCD_ERROR_BLUE=${this.color.error.blue}
neopixel.lib_deps =
  adafruit/Adafruit NeoPixel@^1.15.4
