;
; Defaults
;

[env]
extends = core
lib_compat_mode = strict
build_flags =
lib_deps =
  SPI
  Wire

[defaults]
hardware.neopixel = false
option.core.sms.adapter = all
option.core.gg.adapter = all
option.core.sg1000.adapter = all
output.serial_type = ASCII
output.lcd_type =
output.build_flags =
output.lib_deps =
input.lib_deps =
