;
; Final Hardware Environments
;

[env:HardwareV5]
extends = hardware:5
build_src_flags =
  ${this.arch.build_src_flags}
  ${this.output.build_flags}
  -D HW_VERSION=${this.hardware.version}
build_flags =
  ${this.arch.build_flags}
extra_scripts =
  ${this.arch.extra_scripts}
lib_deps =
  ${this.arch.lib_deps}
  ${this.output.lib_deps}
  ${this.input.lib_deps}



[env:HardwareV4]
extends = hardware:4
build_src_flags =
  ${this.arch.build_src_flags}
  ${this.output.build_flags}
  -D HW_VERSION=${this.hardware.version}
build_flags =
  ${this.arch.build_flags}
extra_scripts =
  ${this.arch.extra_scripts}
lib_deps =
  ${this.arch.lib_deps}
  ${this.output.lib_deps}
  ${this.input.lib_deps}



[env:HardwareV3]
extends = hardware:3
build_src_flags =
  ${this.arch.build_src_flags}
  ${this.output.build_flags}
  -D HW_VERSION=${this.hardware.version}
build_flags =
  ${this.arch.build_flags}
extra_scripts =
  ${this.arch.extra_scripts}
lib_deps =
  ${this.arch.lib_deps}
  ${this.output.lib_deps}
  ${this.input.lib_deps}



[env:HardwareV2]
extends = hardware:2
build_src_flags =
  ${this.arch.build_src_flags}
  ${this.output.build_flags}
  -D HW_VERSION=${this.hardware.version}
build_flags =
  ${this.arch.build_flags}
extra_scripts =
  ${this.arch.extra_scripts}
lib_deps =
  ${this.arch.lib_deps}
  ${this.output.lib_deps}
  ${this.input.lib_deps}



[env:HardwareV1]
extends = hardware:1
build_src_flags =
  ${this.arch.build_src_flags}
  ${this.output.build_flags}
  -D HW_VERSION=${this.hardware.version}
build_flags =
  ${this.arch.build_flags}
extra_scripts =
  ${this.arch.extra_scripts}
lib_deps =
  ${this.arch.lib_deps}
  ${this.output.lib_deps}
  ${this.input.lib_deps}



[env:SerialASCII]
extends = hardware:serial:ascii
build_src_flags =
  ${this.arch.build_src_flags}
  ${this.output.build_flags}
  -D HW_VERSION=${this.hardware.version}
build_flags =
  ${this.arch.build_flags}
extra_scripts =
  ${this.arch.extra_scripts}
lib_deps =
  ${this.arch.lib_deps}
  ${this.output.lib_deps}
  ${this.input.lib_deps}



[env:SerialANSI]
extends = hardware:serial:ansi
build_src_flags =
  ${this.arch.build_src_flags}
  ${this.output.build_flags}
  -D HW_VERSION=${this.hardware.version}
build_flags =
  ${this.arch.build_flags}
extra_scripts =
  ${this.arch.extra_scripts}
lib_deps =
  ${this.arch.lib_deps}
  ${this.output.lib_deps}
  ${this.input.lib_deps}
