;
; SaveTheHero HW3-ALTER
;

[hardware:savethehero:3]
extends =
  board:ATmega2560:standard       ; Standard bootloader
  output:oled                     ; OLED module display
  input:button2                   ; 2-button input
hardware.version = 3              ; Hardware version 3
oscr.powersaving = true           ; Enable powersaving
oscr.config = true                ; Enable config
oscr.updater = true               ; Enable updater
hardware.atmega = module          ; ATmega2560 module
hardware.rtc_type = DS3231
hardware.vselect = false          ; Never vselect

option.core.sms.adapter = raphnet ; Use raphnet (SaveTheHero) for MD slot -> SMS slot adapter
option.core.gg.adapter = retrode  ; Use retrode (SaveTheHero) for MD slot -> GG slot adapter

[env:SaveTheHeroV3]
extends = hardware:savethehero:3
build_src_flags =
  ${this.arch.build_src_flags}
  ${this.output.build_flags}
  -D HW_VERSION=${this.hardware.version}
build_flags =
  ${this.arch.build_flags}
extra_scripts =
  pre:scripts/savethehero.py
  ${this.arch.extra_scripts}
lib_deps =
  ${this.arch.lib_deps}
  ${this.output.lib_deps}
  ${this.input.lib_deps}
