[hardware:starshade:5]
extends =
  board:ATmega2560:minimal:obm  ; Minimal bootloader with integrated ATmega2560 support
  output:lcd:starshade          ; StarshadeRETRO OSCR module display
  input:rotary                  ; StarshadeRETRO OSCR module input
hardware.version = 5            ; hardware version
oscr.powersaving = true         ; Enable powersaving
oscr.mega3v3fix = false         ; Should never be needed
oscr.config = true              ; Enable config
oscr.updater = true             ; Enable updater
hardware.atmega = integrated    ; Integrated ATmega2560
hardware.clockgen = true        ; Integrated Clock Gen
hardware.rtc = true             ; Integrated RTC
hardware.rtc_type = DS3231
hardware.vselect = true         ; Integrated vselect

option.core.sms.adapter = hw5   ; Use HW5's SMS slot
option.core.gg.adapter = hw5    ; Use HW5's GG slot

; Dump faster
option.performance.flags = inline-n64

option.lib.sd.fast = yes        ; Fast SD
option.lib.sd.min = yes         ; Minimal lib - the removed features aren't needed for provided SD card


[env:StarshadeV5]
extends = hardware:starshade:5
build_src_flags =
  ${this.arch.build_src_flags}
  ${this.output.build_flags}
  -D HW_VERSION=${this.hardware.version}
build_flags =
  ${this.arch.build_flags}
extra_scripts =
  ${this.arch.extra_scripts}
lib_deps =
  ${this.arch.lib_deps}
  ${this.output.lib_deps}
  ${this.input.lib_deps}

